name:  Bug Report
description: Reporta un bug o problema en los scripts de b煤squeda
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por reportar este bug! 
        
        Por favor, proporciona la informaci贸n solicitada para ayudarnos a resolver el problema r谩pidamente.

  - type: checkboxes
    id: terms
    attributes:
      label: Verificaci贸n previa
      description: Confirma que has revisado estos puntos antes de crear el issue
      options:
        - label: He buscado en los issues existentes y no hay uno similar
          required: true
        - label: He le铆do la documentaci贸n en README.md
          required: true
        - label: Estoy usando una versi贸n soportada del script
          required: true

  - type: dropdown
    id: script-type
    attributes:
      label: Tipo de Script
      description: 驴En qu茅 script ocurre el problema?
      options:
        - buscar_archivos.ps1 (PowerShell)
        - buscar_archivos.sh (Bash)
        - buscar_simple.sh (Bash simple)
      validations:
        required: true

  - type: input
    id: version
    attributes:
      label: Versi贸n del Script
      description: 驴Qu茅 versi贸n del script est谩s usando?
      placeholder: "v2.0.0"
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: Informaci贸n del Sistema
      description: Proporciona detalles de tu sistema
      placeholder: |
        - OS: Windows 11 / Ubuntu 22.04 / macOS 13
        - PowerShell Version: 5.1 / 7.3
        - Bash Version: 4.4 / 5.1
      value: "OS: \nPowerShell/Bash Version: "
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 驴Qu茅 ocurri贸?
      description: Describe el problema que experimentaste
      placeholder: Describe claramente el comportamiento inesperado
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamiento Esperado
      description: 驴Qu茅 esperabas que ocurriera?
      placeholder: Describe qu茅 deber铆a haber pasado
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Pasos para Reproducir
      description: Lista los pasos exactos para reproducir el problema
      placeholder: |
        1. Ejecutar comando: `.\buscar_archivos.ps1 -Patron "*.txt"`
        2. En directorio: `C:\Users\test`
        3. Ver error: ...
    validations:
      required: true

  - type: textarea
    id: command-used
    attributes:
      label: Comando Ejecutado
      description: El comando exacto que caus贸 el problema
      placeholder: ".\buscar_archivos.ps1 -Patron '*.txt' -Ruta 'C:\test' -MaxResults 100"
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Salida de Error
      description: Copia y pega cualquier mensaje de error o salida inesperada
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Contexto Adicional
      description: Cualquier informaci贸n adicional que pueda ser relevante
      placeholder: |
        - 驴El problema ocurre siempre o solo a veces?
        - 驴Hay alg煤n patr贸n en cuando ocurre?
        - 驴Funciona en otros directorios/situaciones?
    validations:
      required: false